Switch to pyproject.toml (using hatchling)
pdfminer/pdfminer.six pull request #1028
Opened 2024-07-31 20:47 UTC by dhdaines

**Pull request**

Switch to `pyproject.toml`.  I used [hatch](https://hatch.pypa.io) or more specifically its build backend `hatchling` because it was convenient, but we could also use plain old setuptools if you prefer!

**How Has This Been Tested?**

```
hatch run build
hatch shell
pip install -e .[dev]
nox
```

**Checklist**

- [x ] I have read [CONTRIBUTING.md](https://github.com/pdfminer/pdfminer.six/blob/master/CONTRIBUTING.md). 
- [x ] I have added a concise human-readable description of the change to [CHANGELOG.md](https://github.com/pdfminer/pdfminer.six/blob/master/CHANGELOG.md).
- [x ] I have tested that this fix is effective or that this feature works.
- [x ] I have added docstrings to newly created methods and classes.
- [x ] I have updated the [README.md](https://github.com/pdfminer/pdfminer.six/blob/master/README.md) and the [readthedocs](https://github.com/pdfminer/pdfminer.six/tree/master/docs/source) documentation. Or verified that this is not necessary.

2024-07-31 21:05 UTC, dhdaines commented
Note that the output sdist and wheels end up being named `pdfminer_six-...` and not `pdfminer.six-...`.  This is *probably* a good thing but I don't know if it will cause problems for PyPI?

2024-08-06 01:49 UTC, dhdaines commented
The test failure above is some random GitHub failure, not an actual problem with this PR.

2025-03-24 22:44 UTC, pietermarsman commented
> Note that the output sdist and wheels end up being named `pdfminer_six-...` and not `pdfminer.six-...`. This is _probably_ a good thing but I don't know if it will cause problems for PyPI?

That is actually a good thing, because PyPi recently send me a notification that our package name should contain `pdfminer_six` but does not.

2025-03-24 22:45 UTC, pietermarsman requested changes

2025-03-24 22:45 UTC, pietermarsman commented on pyproject.toml
> +packages = ["pdfminer"]
I like switching to pyproject.toml, because it is becoming the default in the python ecosystem afaik. But I'm not sure about hatch(ling). As far as I can understand it from my 10 min Google search, it is a tool that does many things, among which is publishing to pypi. Its functionality overlaps quite a bit with `uv` as well, and I'm thinking of moving to that in the future. 

What do you think of having this MR, but without hatch(ling)? 

And building with the python build package as described [here on the python packaging user guide](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#checking-out-the-project-and-building-distributions)?

2025-03-24 22:52 UTC, dhdaines commented on pyproject.toml
> +packages = ["pdfminer"]
Yes, we could quite easily just use plain old setuptools without any issues, there isn't anything particularly complicated in the build.  The Python build package is helpful as well.

2025-03-24 22:52 UTC, dhdaines commented on pyproject.toml
> +packages = ["pdfminer"]
I can take a bit of time to revise the PR to just use setuptools in the next couple of days.

2025-03-25 01:20 UTC, dhdaines commented
Okay, should be good with plain setuptools now!  I can't test the github workflows though...

2025-03-26 19:08 UTC, pietermarsman approved these changes
Nice one! Just one remark. 

Will fix the publish action if if fails the next time I publish a version.

2025-03-26 19:08 UTC, pietermarsman commented on pyproject.toml
> +    { name = "Yusuke Shinyama + Philippe Guglielmetti", email = "pdfminer@goulu.net" },
```suggestion
    { name = "Yusuke Shinyama" },
    { name = "Philippe Guglielmetti", email = "pdfminer@goulu.net" },
    { name = "Pieter Marsman" },
```

What do you think of using 1 dict per author? 

And I think it is time to add my name as well.

2025-03-26 23:52 UTC, dhdaines commented on pyproject.toml
> +    { name = "Yusuke Shinyama + Philippe Guglielmetti", email = "pdfminer@goulu.net" },
Oh, yes, indeed, it should be one dict per author and as maintainer you should be there too...

2025-03-27 06:25 UTC, merged