Allow suppression of (cid:N) in pdf2txt
pdfminer/pdfminer.six pull request #1070
Opened 2024-11-27 17:34 UTC by dhdaines

Closes: #1056

This is probably a feature people have wanted for a while.  It may be a better idea to make it a configuration option but it is really not clear where this could go in the various devices and converters and such.

I would advise against putting it in `LAParams`  because the simple fact of having an `LAParams` that is not `None` has wide-ranging side-effects on layout analysis.

It has a test :)

**Checklist**

- [x] I have read [CONTRIBUTING.md](https://github.com/pdfminer/pdfminer.six/blob/master/CONTRIBUTING.md). 
- [x] I have added a concise human-readable description of the change to [CHANGELOG.md](https://github.com/pdfminer/pdfminer.six/blob/master/CHANGELOG.md).
- [x] I have tested that this fix is effective or that this feature works.
- [x] I have added docstrings to newly created methods and classes.
- [x] I have updated the [README.md](https://github.com/pdfminer/pdfminer.six/blob/master/README.md) and the [readthedocs](https://github.com/pdfminer/pdfminer.six/tree/master/docs/source) documentation. Or verified that this is not necessary.

2025-03-27 07:36 UTC, pietermarsman requested changes
Like the idea! 

But would prefer it if we use `LAParams` for this, so would like to know more about why you said it should not.

2025-03-27 07:36 UTC, pietermarsman commented on tools/pdf2txt.py
> +        "--ignore-unmapped",
```suggestion
        "--ignore-unmapped-characters",
```

2025-03-27 07:36 UTC, pietermarsman commented on tools/pdf2txt.py
> +        help="Ignore unmapped characters rather than outputting" "(cid:N) in the text",
```suggestion
        help="Ignore unmapped characters rather than outputting (cid:N) in the text",
```

2025-03-27 07:36 UTC, pietermarsman commented on tools/pdf2txt.py
> +        PDFLayoutAnalyzer.handle_undefined_char = lambda *args: ""  # type: ignore
This increases technical debt. I prefer to reduce tech debt and fix bugs over adding features. 

I would like to understand more about why using `LAParams` is not a good option for you. In my understanding, `LAParams` is the way to communicate parameters from the command line to the `PDFLayoutAnalyzer`.

2025-03-28 21:37 UTC, dhdaines commented on tools/pdf2txt.py
> +        PDFLayoutAnalyzer.handle_undefined_char = lambda *args: ""  # type: ignore
Indeed, this is a hack... maybe there should be a better way to communicate "don't do layout analysis" to `PDFLayoutAnalyzer`, see my reply to your other comment.

2025-03-28 21:40 UTC, dhdaines commented
> Like the idea!
> 
> But would prefer it if we use `LAParams` for this, so would like to know more about why you said it should not.

The issue is that passing `None` and passing `LAParams()` to the layout analyzer have very different outcomes.

The first one, passing `None`, will not actually do any layout analysis, which is indeed a bit of a silly thing to do with a layout analyzer, but various third-party code most notably `pdfplumber` depends on it.

If by contrast you pass an `LAParams` with default values, then you get layout analysis, meaning it will make text boxes, text lines, etc.  There's no way to say "just give me low-level items, but, oh, also, I don't want `(cid:N)`"

2025-03-29 22:06 UTC, pietermarsman commented
So you are saying that if we add it to `LAParams`, the `(cid:N)` can only be ignored if `LAParams` is actually given, and not when it is `None`?

2025-03-30 14:27 UTC, dhdaines commented
> So you are saying that if we add it to `LAParams`, the `(cid:N)` can only be ignored if `LAParams` is actually given, and not when it is `None`?

Yes, exactly.

> Another option is to simply accept that we only support ignoring `(cid:N)` for usages with layout analysis enabled. Wouldn't that suit most needs? In that case, pdfplumber can add its own logic / hack.

That's probably okay.  Now that I think of it I'm not sure what other users rely on the behaviour of `LAParams=None` (Unstructured, OCRmyPDF, and pdfannots  do use the default `LAParams` and the resulting layout analysis, for instance).

2025-03-31 07:17 UTC, pietermarsman commented
In that case, my preference would indeed be to add the parameter to `LAParams`. If we ever get the request to remove `(cid:n)` without enabling layout analysis, we can deal with that then (e.g. by adding a `enable_layout_analysis=True` parameter to `LAParams` as well).

2025-03-31 15:37 UTC, dhdaines commented
> In that case, my preference would indeed be to add the parameter to `LAParams`. If we ever get the request to remove `(cid:n)` without enabling layout analysis, we can deal with that then (e.g. by adding a `enable_layout_analysis=True` parameter to `LAParams` as well).

In fact now that I think of it, `pdfplumber` can just handle this internally, since it operates on characters and thus can simply give the option to discard any `LTChar` it finds with a text of the form `(cid:N)`.

2025-04-28 15:08 UTC, pietermarsman commented
@dhdaines So this can be closed?

2025-04-28 17:21 UTC, dhdaines commented
> @dhdaines So this can be closed?

Yes! I've just closed it.

2025-04-28 17:21 UTC, closed without merging