Quick fix to enable switching caching on and off
pdfminer/pdfminer.six pull request #475
Opened 2020-08-21 14:22 UTC by danich1

Closes #474 

This is a quick fix for a bug mentioned in #474.
To reiterate: high_level script that makes `extract_text` and `extract_pages` always use caching despite the user's preference.
This PR fixes that issue and updates the parameters and in-code documentation to be consistent with `extract_text_to_fp`.

2020-08-24 15:19 UTC, jstockwin requested changes
Hey @danich1! Thanks for submitting a fix.

This looks good to me, but we'll wait for @pietermarsman's green-light before merging.

One small thing: please could you update the CHANGELOG file to reflect the fix?

2020-09-01 18:05 UTC, danich1 commented
Changed the CHANGELOG.md to reflect my fix. Hope this helps!

2020-09-10 19:08 UTC, pietermarsman approved these changes

2020-09-10 19:09 UTC, merged

2020-09-10 19:09 UTC, pietermarsman commented
@danich1 Thanks!