Fix out-of-bound access on some PDFs.
pdfminer/pdfminer.six pull request #483
Opened 2020-08-31 10:47 UTC by Flameeyes

Replace the non-emptiness check with a minimum length check — you can't get the second to last item in a list of less than two items.

2020-09-12 10:32 UTC, pietermarsman commented
Hi @Flameeyes, thanks for the suggestion. Can you create an issue first? Maybe also add an example PDF that shows the problematic behavior. 

I'm closing this PR since it might introduce new problems. E.g. if `x == None` the `len(x)` fails.

2020-09-12 11:43 UTC, Flameeyes commented
Unfortunately, I cannot provide an example PDF because the PDF having an issue is a bank statement, which is one of the strongest forms of PII. That's the reason why I didn't file an issue — there's nothing I can provide beside the stack trace.

I'd like to point out that closing a first-contribution pull request is not a very friendly presentation. GitHub has a review system where you can request changes, instead of closing a pull request. That's significantly less adversarial than closing.

Furthermore, your assertion regarding the change's ability to introduce new problem is actually incorrect. `x` is assigned an empty list (`[]`) at the beginning of the block the `if` is in, so it can never be `None`. So `len(x)` is always valid.

You're welcome to reopen and merge this pull request if that made you change your mind.

2020-09-17 19:32 UTC, pietermarsman commented
I was indeed a bit quick in closing this PR. By looking a bit more to the context of your change I now see that the `len(x)` check is indeed a much better alternative than checking for an empty list. Sorry for my impatience!

2020-09-17 19:34 UTC, pietermarsman requested changes
To finish up this PR, can you add a line to the changelog?

2020-09-18 19:01 UTC, Flameeyes commented
> To finish up this PR, can you add a line to the changelog?

Yup, done!

Thank you for circling back on this one :)

2020-10-10 13:18 UTC, pietermarsman approved these changes

2020-10-10 13:18 UTC, merged

2020-10-10 13:18 UTC, pietermarsman commented
Thanks for the work (and the patience)!