do not depend on nose
pdfminer/pdfminer.six pull request #489
Opened 2020-09-08 16:21 UTC by pgajdos

Use unittest only. nose is deprecated and will stop functioning in near future python version.

2020-09-08 16:57 UTC, pgajdos commented
If I should add something to CHANGELOG.md, let me know.

2020-09-12 12:36 UTC, pietermarsman requested changes

2020-09-12 12:36 UTC, pietermarsman commented on tests/test_converter.py
> +import unittest
I prefer to use pytest for everything, and not use a mix of unittest and pytest. Could you pytest'ify all the tests? 

E.g. many tests can be parametrized. And a lot of tests don't need to be grouped in a class anymore.

I'm ok with a proper rewrite/cleanup of the tests.

2020-10-10 14:17 UTC, pietermarsman commented
@pgajdos do you have time to continue to work on this in the near future?

2020-10-12 06:56 UTC, pgajdos commented
Apologize, I have missed notification.

@pietermarsman, reading comment from Sep 12, I will probably rather leave it to you.

2020-10-12 06:56 UTC, closed without merging

2020-10-12 10:39 UTC, pietermarsman commented
Ok. Thanks for the effort!