really drop python<=3.7 support
pdfminer/pdfminer.six pull request #956
Opened 2024-04-09 18:56 UTC by kloczek

**Pull request**
Filter all code over `pyupgrade --py38-plus`.

**How Has This Been Tested?**
I;m using my typical packaging procedure:
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix> using `installer` module
- run pytest with $PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>
- build is performed in env which is *`cut off from access to the public network`* (pytest is executed with `-m "not network"`)

**Checklist**

- [x] I have read [CONTRIBUTING.md](https://github.com/pdfminer/pdfminer.six/blob/master/CONTRIBUTING.md). 
- [ ] I have added a concise human-readable description of the change to [CHANGELOG.md](https://github.com/pdfminer/pdfminer.six/blob/master/CHANGELOG.md).
- [x] I have tested that this fix is effective or that this feature works.
- [ ] I have added docstrings to newly created methods and classes.
- [ ] I have updated the [README.md](https://github.com/pdfminer/pdfminer.six/blob/master/README.md) and the [readthedocs](https://github.com/pdfminer/pdfminer.six/tree/master/docs/source) documentation. Or verified that this is not necessary.

2024-06-27 06:48 UTC, pietermarsman requested changes
Love it! 

Only one comment: what do you think of using f-strings everywhere? I know [pyupgrade is intentionally timid](https://github.com/asottile/pyupgrade?tab=readme-ov-file#f-strings) when converting to f-strings, but I think it is more readable in our almost all of our cases.

2024-06-27 06:48 UTC, pietermarsman commented on pdfminer/converter.py
> +                s = '<figure name="{}" bbox="{}">\n'.format(item.name, bbox2str(item.bbox))
What do you think of using an f-string here as well? 

And in the other locations where `.format()` is used.

2024-07-06 13:40 UTC, merged

2024-07-06 13:44 UTC, pietermarsman commented
@kloczek Thanks for your contribution!

2024-07-06 20:24 UTC, kloczek commented
Thank you